# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 啊大
email: chenyue_jia@126.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎光临~
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/JoiseOLDBIG" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  JoiseOLDBIG

# Build settings
markdown: kramdown

theme: jekyll-theme-slate